"""init

Revision ID: 00b3c27a13bc
Revises: 
Create Date: 2026-03-08 19:12:45.478149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '00b3c27a13bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('async_presentation_generation_tasks',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imageasset',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_uploaded', sa.Boolean(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extras', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyvaluesqlmodel',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyvaluesqlmodel_key'), 'keyvaluesqlmodel', ['key'], unique=False)
    op.create_table('presentation_layout_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('presentation', sa.Uuid(), nullable=False),
    sa.Column('layout_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('layout_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('layout_code', sa.Text(), nullable=True),
    sa.Column('fonts', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_presentation_layout_codes_presentation'), 'presentation_layout_codes', ['presentation'], unique=False)
    op.create_table('presentations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('n_slides', sa.Integer(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_paths', sa.JSON(), nullable=True),
    sa.Column('outlines', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('layout', sa.JSON(), nullable=True),
    sa.Column('structure', sa.JSON(), nullable=True),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.Column('tone', sa.String(), nullable=True),
    sa.Column('verbosity', sa.String(), nullable=True),
    sa.Column('include_table_of_contents', sa.Boolean(), nullable=True),
    sa.Column('include_title_slide', sa.Boolean(), nullable=True),
    sa.Column('web_search', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook_subscriptions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('event', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_subscriptions_event'), 'webhook_subscriptions', ['event'], unique=False)
    op.create_table('slides',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('presentation', sa.Uuid(), nullable=True),
    sa.Column('layout_group', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('layout', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('html_content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('speaker_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['presentation'], ['presentations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slides_presentation'), 'slides', ['presentation'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slides_presentation'), table_name='slides')
    op.drop_table('slides')
    op.drop_index(op.f('ix_webhook_subscriptions_event'), table_name='webhook_subscriptions')
    op.drop_table('webhook_subscriptions')
    op.drop_table('templates')
    op.drop_table('presentations')
    op.drop_index(op.f('ix_presentation_layout_codes_presentation'), table_name='presentation_layout_codes')
    op.drop_table('presentation_layout_codes')
    op.drop_index(op.f('ix_keyvaluesqlmodel_key'), table_name='keyvaluesqlmodel')
    op.drop_table('keyvaluesqlmodel')
    op.drop_table('imageasset')
    op.drop_table('async_presentation_generation_tasks')
    # ### end Alembic commands ###
